apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-evershop-config
data:
  DB_HOST: {{ .Values.evershop.db.host }}
  DB_PORT: "{{ .Values.evershop.db.port }}"
  DB_NAME: {{ .Values.evershop.db.name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgresql-config
data:
  POSTGRES_USER: {{ .Values.postgresql.db.user }}
  POSTGRES_DB: {{ .Values.postgresql.db.name }}