apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-evershop-secrets
type: Opaque
data:
  DB_PASSWORD: {{ .Values.evershop.db.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgresql.db.password | b64enc }}