evershop:
  image:
    repository: abdalluhm/todolist
    tag: latest
  resources:
    requests:
      memory: "50Mi"
      cpu: "50m"
    limits:
      memory: "50Mi"
      cpu: "50m"
  service:
    port: 80
    targetPort: 3000
  db:
    host: todolist-postgresql-service
    port: 5432
    name: postgres
    user: postgres
    password: postgres
  hpa:
    minReplicas: 1
    maxReplicas: 3

postgresql:
  image:
    repository: postgres
    tag: "16"
  resources:
    requests:
      memory: "50Mi"
      cpu: "50m"
    limits:
      memory: "50Mi"
      cpu: "50m"
  service:
    port: 5432
  db:
    name: postgres
    user: postgres
    password: postgres
