name: Build and Deploy

on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout common repo
        uses: actions/checkout@v4


      - name: Deploy Daftarpay to dev EC2
        run: |
          ssh ubuntu@1.1.1.1 "
          touch xxxxx
          "
