name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: npm

      - name: Install dependencies
        run: npm ci
        shell: bash

      # Optional: If you have a build step, leave this; otherwise, it can be removed.
      - name: Build project
        run: npm run build --if-present
        shell: bash

      - name: Run tests
        run: npm test
        shell: bash

  build-and-push:
    runs-on: ubuntu-latest
    needs: test-ci
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-node-js:${{github.run_number}}
      - name: Build docker image
        run: |-
          docker build -t abdalluhm/mynodejs:latest .

      - name: Publish docker image
        run: |-
          docker push abdalluhm/mynodejs:latest