name: Node.js prod

on:
  # push:
  #   branches:
  #     - main

  pull_request:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout my code
        uses: actions/checkout@v3

      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: npm

      - name: Install dependencies
        run: npm ci

      # Optional: If you have a build step, leave this; otherwise, it can be removed.
      - name: Build the app
        run: npm run build --if-present


      - name: Run tests
        run: npm test


  build-and-push:
    runs-on: ubuntu-latest
    #needs: testing
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/demo-image:${{github.sha}}
      
      # - name: Build docker imagedfiovgu
      #   run: |-
      #     docker build -t abdalluhm/mynodejs:latest .

      # - name: Publish docker image
      #   run: |-
      #     docker push abdalluhm/mynodejs:latest